apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dex
  namespace: auth-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "tls-ca-issuer"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - dex.rahmatawe.com
    secretName: dex
  rules:
  - host: dex.rahmatawe.com
    http:
      paths:
      - backend:
          serviceName: dex
          servicePort: 5556
