apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gangway
  namespace: auth-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "tls-ca-issuer"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - kubectl.rahmatawe.com
    secretName: gangway
  rules:
  - host: kubectl.rahmatawe.com
    http:
      paths:
      - backend:
          serviceName: gangway-svc
          servicePort: http
