apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: auth-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --cookie-secure=false
        - --provider=oidc
        - --client-id=rahmatawe-app
        - --client-secret=XmT7EHo27skGchX0yLQNTYXibm3aNkx5
        - --oidc-issuer-url=https://dex.rahmatawe.com
        - --http-address=0.0.0.0:8080
        - --upstream=file:///dev/null
        - --email-domain=*
        - --set-authorization-header=true
#        - --tls-cert=/cacerts/ca.crt
        - --ssl-insecure-skip-verify
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: fOksHBeg7wH1E9OPThGh8g==
        image: sguyennet/oauth2-proxy:header-2.2
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: ca
            mountPath: /cacerts/
      volumes:
        - name: ca
          secret:
            secretName: dex

