apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo1-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "tls-ca-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - echo1.kubernetes.riupie.com
    secretName: my-dev-tls
  rules:
  - host: echo1.kubernetes.riupie.com
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80
